<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="7508" started-at="2020-02-14T17:09:06Z" finished-at="2020-02-14T17:09:13Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="7508" started-at="2020-02-14T17:09:06Z" finished-at="2020-02-14T17:09:13Z">
      <class name="com.api.testng.UsersApi.GetAPI">
        <test-method status="PASS" signature="testapi()[pri:0, instance:com.api.testng.UsersApi.GetAPI@9f70c54]" name="testapi" duration-ms="3902" started-at="2020-02-14T22:39:06Z" finished-at="2020-02-14T22:39:10Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testapi -->
      </class> <!-- com.api.testng.UsersApi.GetAPI -->
      <class name="com.api.testng.UsersApi.PostAPI">
        <test-method status="FAIL" signature="numberpost()[pri:0, instance:com.api.testng.UsersApi.PostAPI@2d3fcdbd]" name="numberpost" duration-ms="3592" started-at="2020-02-14T22:39:10Z" finished-at="2020-02-14T22:39:13Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected:<DB returned 23505> but was:<Succcess>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected:<DB returned 23505> but was:<Succcess>
	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:101)
	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:108)
	at com.api.testng.UsersApi.PostAPI.numberpost(PostAPI.java:42)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:377)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:138)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:465)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:451)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- numberpost -->
      </class> <!-- com.api.testng.UsersApi.PostAPI -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
